#!/usr/bin/env ruby
Encoding.default_external = Encoding::UTF_8
require 'feedjira'
urls = `cat ~/.config/rss_reader/urls | grep -v ^# | grep -v ^system`.split("\n")
feeds = []
feed_titles = []
urls.each do |x|
  feed = Feedjira::Feed.fetch_and_parse x
  feeds.push(feed)
  feed_titles.push(feed.title)
end
while true
  selected_feed = `echo "#{feed_titles.join("\n")}" | fzf --color=16`.chomp
  if selected_feed != ""
    selected_feed_position = feed_titles.index(selected_feed)
    selected_feed_titles = []
    feeds[selected_feed_position].entries.each do |x|
      selected_feed_titles.push(x.title)
    end
    selected_entry = `(echo "BACK" && echo "#{selected_feed_titles.join("\n")}") | fzf --color=16`.chomp
    if selected_entry != "" && selected_entry != "BACK"
      selected_entry_position = selected_feed_titles.index(selected_entry)
      url = feeds[selected_feed_position].entries[selected_entry_position].url
      app = `cat ~/.config/rss_reader/applications | fzf --color=16`.chomp
      system "#{app} #{url} &"
    end
  end
  if selected_feed == "" || selected_entry == ""
    break
  end
end
