#!/usr/bin/env ruby
require 'feedjira'
source = `ls ~/.rss_reader | grep urls | cut -d "-" -f 1 | dmenu -p "Source: " -i -l 20`.chomp
while source != ""
  if source == "youtube"
    application = "mpv"
  elsif source == "news"
    application = "surf"
  end
  
  url = `(echo "BACK" && cat ~/.rss_reader/#{source}-urls) | dmenu -i -l 20 | cut -d "|" -f 2 | cut -d " " -f 2`.chomp
  if url == ""
    break
  elsif url == "BACK"
    system "exec ~/scripts/content/rss"
    break
  elsif url != ""
    feed = Feedjira::Feed.fetch_and_parse url
    entries = []
    feed.entries.each do |entry|
      entries.push("#{entry.title.gsub(/"/, "'")} #{" " * 200} #{entry.url}")
    end
    entries = entries.join("\n")

    selected = `echo "BACK\n#{entries}" | dmenu -i -l 30 | awk '{print $NF}'`.chomp
    
    if selected != "" && selected != "BACK"
      system "#{application} #{selected}"
    end
    unless selected == "BACK"
      break
    end
  end
end
